// decap-svelte/frontend/src/lib/summaries/LearningGuide.svelte
<script lang="ts">
	import { learningGuides } from './learning-data';
	import type { SummaryTopic } from './topics';
	import './learning.css';
	let { topic }: { topic: SummaryTopic } = $props();
	let guide = $derived(learningGuides[topic.slug]);
	let answers = $state<Record<string, number>>({});
	let checked = $state(false);
	let complete = $derived(guide.questions.every((question) => answers[question.id] !== undefined));
	let score = $derived(
		guide.questions.filter((question) => answers[question.id] === question.answer).length
	);
</script>

<div class="ds-learning-guide">
	<nav class="ds-study-nav" aria-label="Learning guide sections">
		<a href="#ds-learning-plan">Learning plan</a><a href="#ds-detailed-lessons">Explanations</a><a
			href="#ds-worked-examples">Worked examples</a
		><a href="#ds-learning-resources">YouTube & references</a><a href="#ds-practice">Practice</a><a
			href="#ds-knowledge">Knowledge check</a
		>
	</nav>
	<section class="ds-section" id="ds-learning-plan">
		<header class="ds-heading">
			<span class="ds-eyebrow">LEARNING PLAN</span>
			<h2>Understand the topic, one step at a time.</h2>
		</header>
		<div class="ds-study-intro glass">
			<div>
				<h3>Before you start</h3>
				<p>{guide.prerequisites}</p>
				<h3>What this guide covers</h3>
				<p>{guide.scope}</p>
			</div>
			<div>
				<h3>By the end, you should be able to</h3>
				<ul>
					{#each guide.objectives as objective (objective)}<li>{objective}</li>{/each}
				</ul>
			</div>
		</div>
		<ol class="ds-roadmap">
			{#each guide.roadmap as step (step.title)}<li>
					<h3>{step.title}</h3>
					<p>{step.action}</p>
					<p class="ds-checkpoint"><strong>Checkpoint:</strong> {step.checkpoint}</p>
				</li>{/each}
		</ol>
	</section>
	<section class="ds-section" id="ds-detailed-lessons">
		<header class="ds-heading">
			<span class="ds-eyebrow">DETAILED EXPLANATIONS</span>
			<h2>Connect each term to a concrete behavior.</h2>
			<p>Read the explanation, then use the example to test the idea.</p>
		</header>
		<div class="ds-study-grid">
			{#each guide.lessons as lesson (lesson.title)}<article class="ds-study-panel glass">
					<h3>{lesson.title}</h3>
					<p>{lesson.explanation}</p>
					<div class="ds-example-note">
						<strong>Example</strong>
						<p>{lesson.example}</p>
					</div>
				</article>{/each}
		</div>
	</section>
	<section class="ds-section" id="ds-worked-examples">
		<header class="ds-heading">
			<span class="ds-eyebrow">WORKED EXAMPLES</span>
			<h2>Follow the reasoning, step by step.</h2>
		</header>
		{#each guide.examples as example (example.title)}<article
				class="ds-study-panel ds-worked-example glass"
			>
				<h3>{example.title}</h3>
				<p>{example.context}</p>
				<pre><code>{example.trace}</code></pre>
				<p>{example.explanation}</p>
			</article>{/each}
	</section>
	<section class="ds-section" id="ds-learning-resources">
		<header class="ds-heading">
			<span class="ds-eyebrow">WATCH & READ</span>
			<h2>YouTube lessons and reliable references.</h2>
			<p>
				Each link opens a new tab. Follow the study task, then compare what you learned with the
				original presentation.
			</p>
		</header>
		<div class="ds-study-grid">
			{#each guide.resources as resource (resource.url)}<article
					class="ds-study-panel ds-learning-resource glass"
				>
					<span class="ds-eyebrow"
						>{resource.kind === 'YouTube' ? '▶ YOUTUBE LESSON' : 'READING REFERENCE'}</span
					>
					<h3>
						<!-- External HTTPS learning resource, not a SvelteKit route. -->
						<!-- eslint-disable-next-line svelte/no-navigation-without-resolve -->
						<a href={resource.url} target="_blank" rel="noopener noreferrer">{resource.title} ↗</a>
					</h3>
					<span class="ds-resource-provider">{resource.provider}</span>
					<p>{resource.focus}</p>
					<div class="ds-example-note">
						<strong>Study task</strong>
						<p>{resource.task}</p>
					</div>
					<p class="ds-resource-context">{resource.context}</p>
					<!-- External HTTPS learning resource, not a SvelteKit route. -->
					<!-- eslint-disable svelte/no-navigation-without-resolve -->
					<a
						class="ds-button ds-secondary"
						href={resource.url}
						target="_blank"
						rel="noopener noreferrer"
						>{resource.kind === 'YouTube' ? 'Watch on YouTube' : 'Open reference'} ↗</a
					>
					<!-- eslint-enable svelte/no-navigation-without-resolve -->
				</article>{/each}
		</div>
	</section>
	<section class="ds-section">
		<header class="ds-heading">
			<span class="ds-eyebrow">COMMON MISUNDERSTANDINGS</span>
			<h2>Check the distinctions that matter.</h2>
		</header>
		<dl class="ds-misconceptions">
			{#each guide.mistakes as mistake (mistake.claim)}<div class="glass">
					<dt>{mistake.claim}</dt>
					<dd>{mistake.correction}</dd>
				</div>{/each}
		</dl>
	</section>
	<section class="ds-section" id="ds-practice">
		<header class="ds-heading">
			<span class="ds-eyebrow">PUT IT INTO PRACTICE</span>
			<h2>Explain it, predict it, then check it.</h2>
			<p>
				Try the task before revealing its expected result. These exercises do not require hardware.
			</p>
		</header>
		<div class="ds-study-grid">
			{#each guide.practice as exercise (exercise.title)}<article class="ds-study-panel glass">
					<h3>{exercise.title}</h3>
					<p>{exercise.task}</p>
					<details>
						<summary>Show expected result</summary>
						<p>{exercise.expected}</p>
					</details>
				</article>{/each}
		</div>
	</section>
	<section class="ds-section" id="ds-knowledge">
		<header class="ds-heading">
			<span class="ds-eyebrow">KNOWLEDGE CHECK</span>
			<h2>Can you explain the important parts?</h2>
			<p>
				Three questions with feedback. Answers stay on this page and do not change your course
				records.
			</p>
		</header>
		<form
			class="ds-study-panel ds-knowledge-form glass"
			onsubmit={(event) => {
				event.preventDefault();
				if (complete) checked = true;
			}}
		>
			{#each guide.questions as question (question.id)}<fieldset>
					<legend>{question.prompt}</legend>{#each question.options as option, index (option)}<label
							><input
								type="radio"
								name={topic.slug + '-' + question.id}
								checked={answers[question.id] === index}
								onchange={() => {
									answers = { ...answers, [question.id]: index };
									checked = false;
								}}
							/><span>{option}</span></label
						>{/each}{#if checked}<p class="ds-answer-feedback">
							<strong
								>{answers[question.id] === question.answer
									? 'Correct.'
									: 'Review this idea.'}</strong
							>
							{question.explanation}
						</p>{/if}
				</fieldset>{/each}
			<div class="ds-actions">
				<button type="submit" class="ds-button" disabled={!complete}>Check my understanding</button
				><button
					type="button"
					class="ds-button ds-secondary"
					onclick={() => {
						answers = {};
						checked = false;
					}}>Reset answers</button
				>
				<p class="ds-quiz-status" aria-live="polite">
					{checked
						? `${score} of ${guide.questions.length} correct. Review the explanations and try again.`
						: 'Choose an answer for every question before checking.'}
				</p>
			</div>
		</form>
	</section>
</div>

// sanity-cms/components/summaries/LearningGuide.tsx
import React, {useState} from 'react'
import {LEARNING_GUIDES, type LearningGuide as GuideData} from './learning-data'
import type {SummaryTopic} from './summary-data'
import {Reveal, SectionHeading} from './visuals'

function KnowledgeCheck({guide, slug}: {guide: GuideData; slug: string}) {
  const [answers, setAnswers] = useState<Record<string, number>>({})
  const [checked, setChecked] = useState(false)
  const complete = guide.questions.every((question) => answers[question.id] !== undefined)
  const score = guide.questions.filter(
    (question) => answers[question.id] === question.answer,
  ).length
  return (
    <form
      className="qs-knowledge-check"
      onSubmit={(event) => {
        event.preventDefault()
        if (complete) setChecked(true)
      }}
    >
      {guide.questions.map((question) => (
        <fieldset key={question.id}>
          <legend>{question.prompt}</legend>
          {question.options.map((option, index) => (
            <label key={option}>
              <input
                type="radio"
                name={`${slug}-${question.id}`}
                checked={answers[question.id] === index}
                onChange={() => {
                  setAnswers({...answers, [question.id]: index})
                  setChecked(false)
                }}
              />
              <span>{option}</span>
            </label>
          ))}
          {checked && (
            <p className="qs-answer-feedback">
              <strong>
                {answers[question.id] === question.answer ? 'Correct.' : 'Review this idea.'}
              </strong>{' '}
              {question.explanation}
            </p>
          )}
        </fieldset>
      ))}
      <div className="qs-check-actions">
        <button type="submit" className="qs-button" disabled={!complete}>
          Check my understanding
        </button>
        <button
          type="button"
          className="qs-button qs-ghost"
          onClick={() => {
            setAnswers({})
            setChecked(false)
          }}
        >
          Reset answers
        </button>
        <p aria-live="polite">
          {checked
            ? `${score} of ${guide.questions.length} correct. Review the explanations and try again.`
            : 'Choose an answer for every question, then check your understanding.'}
        </p>
      </div>
    </form>
  )
}

export function LearningGuide({topic}: {topic: SummaryTopic}) {
  const guide = LEARNING_GUIDES[topic.slug]
  return (
    <div className="qs-learning-guide">
      <nav className="qs-study-nav" aria-label="Learning guide sections">
        <a href="#qs-learning-plan">Learning plan</a>
        <a href="#qs-detailed-lessons">Detailed explanations</a>
        <a href="#qs-worked-examples">Worked examples</a>
        <a href="#qs-learning-resources">YouTube & references</a>
        <a href="#qs-practice">Practice</a>
        <a href="#qs-knowledge">Knowledge check</a>
      </nav>
      <section className="qs-summary-section" id="qs-learning-plan">
        <SectionHeading
          label="LEARNING PLAN"
          title="Know what you are learning—and in what order."
          description={guide.level}
        />
        <div className="qs-study-intro">
          <div>
            <h3>Before you start</h3>
            <p>{guide.prerequisites}</p>
            <h3>What this guide covers</h3>
            <p>{guide.scope}</p>
          </div>
          <div>
            <h3>By the end, you should be able to</h3>
            <ul>
              {guide.objectives.map((objective) => (
                <li key={objective}>{objective}</li>
              ))}
            </ul>
          </div>
        </div>
        <ol className="qs-roadmap">
          {guide.roadmap.map((step) => (
            <li key={step.title}>
              <h3>{step.title}</h3>
              <p>{step.action}</p>
              <p className="qs-checkpoint">
                <strong>Checkpoint:</strong> {step.checkpoint}
              </p>
            </li>
          ))}
        </ol>
      </section>
      {topic.slug === 'raspberry-pi-1' && (
        <section className="qs-summary-section" aria-label="Raspberry Pi 1 model comparison">
          <SectionHeading
            label="MODEL DETAILS"
            title="Identify the Pi 1 you actually have."
            description="These are model differences. Board revisions can introduce further details; use the official reference for your exact board."
          />
          <div className="qs-table-scroll">
            <table className="qs-model-table">
              <caption>Raspberry Pi 1 connector comparison</caption>
              <thead>
                <tr>
                  <th scope="col">Model</th>
                  <th scope="col">Header</th>
                  <th scope="col">USB 2.0 ports</th>
                  <th scope="col">Boot storage</th>
                  <th scope="col">Ethernet</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">A</th>
                  <td>26 pins</td>
                  <td>1</td>
                  <td>SD</td>
                  <td>No</td>
                </tr>
                <tr>
                  <th scope="row">B</th>
                  <td>26 pins</td>
                  <td>2</td>
                  <td>SD</td>
                  <td>Yes</td>
                </tr>
                <tr>
                  <th scope="row">A+</th>
                  <td>40 pins</td>
                  <td>1</td>
                  <td>microSD</td>
                  <td>No</td>
                </tr>
                <tr>
                  <th scope="row">B+</th>
                  <td>40 pins</td>
                  <td>4</td>
                  <td>microSD</td>
                  <td>Yes</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p className="qs-study-source">
            Source:{' '}
            <a
              href="https://www.raspberrypi.com/documentation/computers/raspberry-pi.html"
              target="_blank"
              rel="noopener noreferrer"
            >
              Raspberry Pi official hardware documentation ↗
            </a>
          </p>
        </section>
      )}
      <section className="qs-summary-section" id="qs-detailed-lessons">
        <SectionHeading
          label="DETAILED EXPLANATIONS"
          title="Connect each term to a concrete behavior."
          description="Read the explanation, then use the example to test whether the idea makes sense."
        />
        <div className="qs-lesson-grid">
          {guide.lessons.map((lesson) => (
            <Reveal key={lesson.title}>
              <article className="qs-study-panel">
                <h3>{lesson.title}</h3>
                <p>{lesson.explanation}</p>
                <div className="qs-example-note">
                  <strong>Example</strong>
                  <p>{lesson.example}</p>
                </div>
              </article>
            </Reveal>
          ))}
        </div>
      </section>
      <section className="qs-summary-section" id="qs-worked-examples">
        <SectionHeading
          label="WORKED EXAMPLES"
          title="Follow the reasoning, step by step."
          description="Use these examples alongside the interactive diagrams and your full lecture."
        />
        {guide.examples.map((example) => (
          <article key={example.title} className="qs-worked-example">
            <h3>{example.title}</h3>
            <p>{example.context}</p>
            <pre>
              <code>{example.trace}</code>
            </pre>
            <p>{example.explanation}</p>
          </article>
        ))}
      </section>
      <section className="qs-summary-section" id="qs-learning-resources">
        <SectionHeading
          label="WATCH & READ"
          title="YouTube lessons and reliable references."
          description="Follow the suggested order. Each link opens a new tab so you can keep this guide and the original lecture available."
        />
        <div className="qs-resource-grid">
          {guide.resources.map((resource) => (
            <article className="qs-study-panel qs-resource" key={resource.url}>
              <span className="qs-resource-kind">
                {resource.kind === 'YouTube' ? '▶ YOUTUBE LESSON' : resource.kind.toUpperCase()}
              </span>
              <h3>
                <a href={resource.url} target="_blank" rel="noopener noreferrer">
                  {resource.title} ↗
                </a>
              </h3>
              <span className="qs-resource-provider">{resource.provider}</span>
              <p>{resource.focus}</p>
              <div className="qs-example-note">
                <strong>Study task</strong>
                <p>{resource.task}</p>
              </div>
              <p className="qs-resource-context">{resource.context}</p>
              <a
                className="qs-button qs-ghost"
                href={resource.url}
                target="_blank"
                rel="noopener noreferrer"
              >
                {resource.kind === 'YouTube' ? 'Watch on YouTube' : 'Open reference'} ↗
              </a>
            </article>
          ))}
        </div>
      </section>
      <section className="qs-summary-section">
        <SectionHeading
          label="COMMON MISUNDERSTANDINGS"
          title="Check these distinctions before moving on."
          description="Compare each common claim with the explanation underneath."
        />
        <dl className="qs-misconceptions">
          {guide.mistakes.map((mistake) => (
            <div key={mistake.claim}>
              <dt>{mistake.claim}</dt>
              <dd>{mistake.correction}</dd>
            </div>
          ))}
        </dl>
      </section>
      <section className="qs-summary-section" id="qs-practice">
        <SectionHeading
          label="PUT IT INTO PRACTICE"
          title="Explain it, predict it, then check it."
          description="Try each task before opening the expected result. These exercises can be completed without purchasing hardware."
        />
        <div className="qs-lesson-grid">
          {guide.practice.map((exercise) => (
            <article key={exercise.title} className="qs-study-panel">
              <h3>{exercise.title}</h3>
              <p>{exercise.task}</p>
              <details>
                <summary>Show expected result</summary>
                <p>{exercise.expected}</p>
              </details>
            </article>
          ))}
        </div>
      </section>
      <section className="qs-summary-section" id="qs-knowledge">
        <SectionHeading
          label="KNOWLEDGE CHECK"
          title="Can you explain the important parts?"
          description="Three questions with explanations. You can reset and try again; this check does not change your course records."
        />
        <KnowledgeCheck key={topic.slug} guide={guide} slug={topic.slug} />
      </section>
    </div>
  )
}
