// sanity-cms/components/summaries/TopicOverviews.tsx
import React from 'react'
import {StateLink} from 'sanity/router'
import {SUMMARY_TOPICS} from './summary-data'
import {LEARNING_GUIDES} from './learning-data'
import {FeatureChips, HardwareModel, Reveal, SectionHeading, summaryTheme} from './visuals'

export function TopicOverviews() {
  return (
    <section className="qs-root qs-overviews" aria-label="Quick Learn topic overviews">
      <SectionHeading
        label="QUICK LEARN"
        title="Topic Overviews"
        description="Explore quick visual summaries of each lecture through interactive diagrams, key concepts, and 3D-inspired visuals."
      />
      <div className="qs-overview-grid">
        {SUMMARY_TOPICS.map((topic) => (
          <Reveal key={topic.slug} className="qs-overview-entry">
            <StateLink
              state={{topic: topic.slug}}
              className="qs-overview-card"
              style={summaryTheme(topic)}
            >
              <div className="qs-card-visual">
                <span className="qs-card-code">{topic.code}</span>
                <HardwareModel topic={topic} compact />
              </div>
              <div className="qs-card-copy">
                <h3>{topic.title}</h3>
                <span className="qs-card-subtitle">Visual Topic Summary</span>
                <p>{topic.description}</p>
                <FeatureChips topic={topic} />
                <span className="qs-card-study-label">WHAT YOU WILL LEARN</span>
                <ul className="qs-card-objectives">
                  {LEARNING_GUIDES[topic.slug].objectives.slice(0, 3).map((objective) => (
                    <li key={objective}>{objective}</li>
                  ))}
                </ul>
                <span className="qs-card-study-meta">
                  5-step learning path · Worked examples · Knowledge check
                </span>
                <span className="qs-button qs-card-button">
                  Explore Summary & Learning Guide <span>→</span>
                </span>
              </div>
            </StateLink>
            <div className="qs-card-watch" style={summaryTheme(topic)}>
              <span>▶ START WITH A VIDEO</span>
              <a
                href={LEARNING_GUIDES[topic.slug].resources[0].url}
                target="_blank"
                rel="noopener noreferrer"
              >
                {LEARNING_GUIDES[topic.slug].resources[0].title} ↗
              </a>
              <small>
                {LEARNING_GUIDES[topic.slug].resources[0].provider} · More videos and references
                inside
              </small>
            </div>
          </Reveal>
        ))}
      </div>
    </section>
  )
}

// decap-svelte/frontend/src/lib/summaries/TopicOverviews.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import Icon from '$lib/Icon.svelte';
	import { summaryTopics } from './topics';
	import { learningGuides } from './learning-data';
	import './learning.css';
	import SummaryVisual from './SummaryVisual.svelte';
	import { visualReveal } from './visual-actions';
</script>

<section class="dashboard-section ds-overviews" aria-labelledby="ds-overviews-title">
	<div class="section-heading">
		<div>
			<div class="eyebrow">QUICK LEARN</div>
			<h2 id="ds-overviews-title">Topic Overviews</h2>
			<p>
				Understand the essentials at a glance through interactive diagrams, key concepts, and visual
				learning experiences.
			</p>
		</div>
		<span class="soft-badge">2 INTERACTIVE OVERVIEWS</span>
	</div>
	<div class="ds-overview-grid">
		{#each summaryTopics as topic (topic.slug)}
			<div class="ds-overview-entry" style="--ds-accent:{topic.accent}">
				<a
					class="ds-overview-card glass"
					style="--ds-accent:{topic.accent}"
					href={resolve('/summary/[slug]', { slug: topic.slug })}
					use:visualReveal
				>
					<div class="ds-card-art">
						<span class="ds-card-label">{topic.title.toUpperCase()}</span><SummaryVisual
							{topic}
							compact
						/>
					</div>
					<div class="ds-card-copy">
						<h3>{topic.title}</h3>
						<span class="ds-card-subtitle">Interactive Visual Overview</span>
						<p>{topic.cardDescription}</p>
						<div class="ds-chips">
							{#each topic.features as feature (feature)}<span>{feature}</span>{/each}
						</div>
						<span class="ds-card-study-label">WHAT YOU WILL LEARN</span>
						<ul class="ds-card-objectives">
							{#each learningGuides[topic.slug].objectives.slice(0, 3) as objective (objective)}<li>
									{objective}
								</li>{/each}
						</ul>
						<span class="ds-card-study-meta"
							>5-step study plan · Worked examples · Knowledge check</span
						>
						<div class="ds-card-bottom">
							<span>Explore Summary & Learning Guide</span><Icon name="arrow" size={18} />
						</div>
					</div>
				</a>
				<div class="ds-card-video glass">
					<span>▶ START WITH A VIDEO</span>
					<!-- External YouTube resource, not a SvelteKit route. -->
					<!-- eslint-disable svelte/no-navigation-without-resolve -->
					<a
						href={learningGuides[topic.slug].resources[0].url}
						target="_blank"
						rel="noopener noreferrer">{learningGuides[topic.slug].resources[0].title} ↗</a
					>
					<!-- eslint-enable svelte/no-navigation-without-resolve -->
					<small
						>{learningGuides[topic.slug].resources[0].provider} · More lessons and references inside</small
					>
				</div>
			</div>
		{/each}
	</div>
</section>
